name: Pre-release

on:
  push:
    tags:
      # Match semver pre-release tags only, e.g. v1.2.3-alpha.1, v0.9.0-rc.0
      - 'v*.*.*-*'

concurrency:
    group: release-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    name: Create pre-release from tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate semver pre-release tag
        run: |
          echo "Tag: $GITHUB_REF_NAME"
          if ! echo "$GITHUB_REF_NAME" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+-[0-9A-Za-z][0-9A-Za-z.-]*$'; then
            echo "Tag must be semver pre-release: vMAJOR.MINOR.PATCH-<id>[.<n>]" >&2
            exit 1
          fi

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run package && npm run package:win

      - name: List build outputs
        run: ls -l dist || find dist -maxdepth 2 -type f

      - name: Generate checksums
        run: |
          (cd dist && sha256sum * > SHA256SUMS.txt)
          echo "Generated SHA256SUMS.txt:" && cat dist/SHA256SUMS.txt

      - name: Publish pre-release with assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          prerelease: true
          draft: false
          files: |
            dist/**
          fail_on_unmatched_files: true
